// Code generated by "stringer -type targetKind -trimprefix kind"; DO NOT EDIT.

package rt

import "strconv"

const _targetKind_name = "MethodFunctionInterfaceInterfaceMethodType"

var _targetKind_index = [...]uint8{0, 6, 14, 23, 38, 42}

func (i targetKind) String() string {
	i -= 1
	if i < 0 || i >= targetKind(len(_targetKind_index)-1) {
		return "targetKind(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _targetKind_name[_targetKind_index[i]:_targetKind_index[i+1]]
}
